name: unrpa
version: git
summary: Extract files from the RPA archive format.
description: |
  unrpa is a CLI tool to extract files from the RPA archive format (from the Ren'Py Visual Novel Engine).
license: GPL-3.0

base: core18
confinement: strict

parts:
  unrpa:
    plugin: python
    python-version: python3
    source: .
    after: [python37]
    stage:
      - -usr/bin/pydoc3
      - -usr/bin/python3
      - -usr/lib/python3.7


  # source: https://forum.snapcraft.io/t/how-do-i-correctly-install-a-custom-python-version-and-a-local-wheel-package/12040/2
  # https://forum.snapcraft.io/t/build-a-snap-with-any-version-of-python-i-want/10420/2
  # https://forum.snapcraft.io/t/building-a-python-snap-package/6766/7
  # https://forum.snapcraft.io/t/snapping-a-python-3-7-app/10483
  python37:
    source: https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
    source-type: tar
    source-checksum: md5/93df27aec0cd18d6d42173e601ffbbfd
    plugin: autotools
    configflags:
      - --prefix=/usr
    build-packages:
      - libbz2-dev
      - libexpat1-dev
      - libffi-dev
      - libgdbm-dev
      - liblzma-dev
      - libncurses5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libzip-dev
      - uuid-dev
    stage-packages:
      - libbz2-1.0
      - libexpat1
      - libffi6
      - libgdbm5
      - liblzma5
      - libncurses5
      - libreadline7
      - libsqlite3-0
      - libssl1.0.0
      - libzip4
      - uuid-runtime
    stage:
      - -usr/lib/python3.7/test
      - -var

apps:
  unrpa:
    command: unrpa
    environment: 
      # https://lists.ubuntu.com/archives/snapcraft/2016-October/001287.html
      # https://askubuntu.com/questions/906199/how-to-setup-pythonpath-for-a-snap-package
      # 
      # to fix pkg_resources.DistributionNotFound: The 'unrpa==2.1.0' distribution was not found and is required by the application
      PYTHONPATH: "$SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.7/site-packages"
    plugs:
     - home
